@jwt = 

@token = 

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Youth Challenge index
GET http://localhost:3000/youth_challenges.json



### Youth Challenges show
GET http://localhost:3000/youth_challenges/12.json

### Youth Challenges update
PATCH http://localhost:3000/youth_challenges/13
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "delete"
}

### Youth Challenges destroy
DELETE http://localhost:3000/youth_challenges/13
Authorization: Bearer {{jwt}}

### PetFinder Token
curl -d "grant_type=client_credentials&client_id={CLIENT-ID}&client_secret={CLIENT-SECRET}" https://api.petfinder.com/v2/oauth2/token

### PetFinder Search
GET https://api.petfinder.com/v2/organizations
Authorization: Bearer {{token}} 

### Animal Shelter index
GET http://localhost:3000/animal_shelters.json


